# kindly generated by appropriated Rails generator

require 'mailjet'

Dotenv.load

Mailjet.configure do |config|
  config.api_key = ENV["MJ_APIKEY_PUBLIC"]
  config.secret_key = ENV["MJ_APIKEY_PRIVATE"]
  config.default_from = 'giraud.nicolas@me.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end


# variable = Mailjet::Send.create(messages: [{
#   'From'=> {
#     'Email'=> 'giraud.nicolas@me.com',
#     'Name'=> 'kitten team'
#   },
#   'To'=> [
#     {
#       'Email'=> 'giraud.nicolas@me.com',
#       'Name'=> 'Nicolas'
#     }
#   ],
#   'Subject'=> 'Greetings from Mailjet.',
#   'TextPart'=> 'My first Mailjet email',
#   'HTMLPart'=> '<h3>Dear passenger 1, welcome to <a href=\'https://www.mailjet.com/\'>Mailjet</a>!</h3><br />May the delivery force be with you!',
#   'CustomID' => 'AppGettingStartedTest'
# }]
# )
# p variable.attributes['Messages']

